# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import maestro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to=maestro.models.deporte_path)),
            ],
        ),
    ]
