# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import maestro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to=maestro.models.deporte_path)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('ruc', models.CharField(max_length=11)),
                ('imagen', models.ImageField(upload_to=maestro.models.empresa_path)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Subdeporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.Deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('latitud', models.CharField(max_length=15)),
                ('longitud', models.CharField(max_length=15)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Distrito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tipocancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Provincia'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.Sucursal'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipocancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Tipocancha'),
        ),
    ]
